[package]
name = "flavoursweb"
version = "0.1.0"
authors = ["Gabriel Fontes <g.fontes@usp.br>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
